version: "3.8"

services:
 web:
  image: nginx
  container_name: web_app
  ports:
   - "80:80"
  volumes:
   - ./index.html:/usr/share/nginx/html/index.html
  depends_on:
   - redis

 redis:
  image: redis
  container_name: redis_db
